language: c
compiler:
  - clang
  - gcc
  
before_install:
  - sudo apt-get update
  - sudo apt-get install xsltproc doxygen
  - echo $LANG
  - echo $LC_ALL

script: 
    - echo "================================================="
    - pwd
    - cd $TRAVIS_BUILD_DIR/build/cmake
    - cmake ../../
    - make
    - echo "================================================="
    - cd $TRAVIS_BUILD_DIR/documentation
    - ./build_docs.sh
    
env:
  - FOO=BAR