language: c
compiler:
  - clang
  - gcc
os:
  - linux
  - osx  
before_install:
  - sudo apt-get update
  - sudo apt-get install xsltproc doxygen
  - echo $LANG
  - echo $LC_ALL

script: 
    - pwd
    - cd $TRAVIS_BUILD_DIR/build/cmake
    - cmake ../../
    - make
    - cd $TRAVIS_BUILD_DIR/build/documentation
    - ./build_docs.sh
env:
  - FOO=BAR