.\" tidy man page for the HTML Tidy
.TH TIDY 1 "5.3.12" "HTML Tidy" "5.3.12"

.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH NAME
\fBtidy\fR - check, correct, and pretty-print HTML(5) files
.SH SYNOPSIS
\fBtidy\fR [\fIoptions\fR] [\fIfile\fR ...] [\fIoptions\fR] [\fIfile\fR ...] ...
.SH DESCRIPTION
Tidy reads HTML, XHTML, and XML files and writes cleaned-up markup.  For HTML variants, it detects, reports, and corrects many common coding errors and strives to produce visually equivalent markup that is both conformant to the HTML specifications and that works in most browsers.
.LP
A common use of Tidy is to convert plain HTML to XHTML.  For generic XML files, Tidy is limited to correcting basic well-formedness errors and pretty printing.
.LP
If no input file is specified, Tidy reads the standard input.  If no output file is specified, Tidy writes the tidied markup to the standard output.  If no error file is specified, Tidy writes messages to the standard error.
.SH OPTIONS
The options detailed here do not include the "standard" command-line options (i.e., those preceded by a single '\fB-\fR') described above in the first section of this man page.
.LP
Single letter options apart from \fB-f\fR and \fB-o\fR may be combined as in:
.LP
.in 1i
\fBtidy -f errs.txt -imu foo.html\fR
.LP
For command line options that expect a numerical argument, a default is assumed if no meaningful value can be found.  
.LP
A list of options for configuring the behavior of Tidy, which can be passed either on the command line, or specified in a configuration file.
.LP
Use \fB--\fR\fIoptionX valueX\fR for the detailed configuration option "optionX" with argument "valueX".  See also below under \fBDetailed Configuration Options\fR as to how to conveniently group all such options in a single config file.  
This section describes the Detailed (i.e., "expanded") Options, which may be specified by preceding each option with \fB--\fR at the command line, followed by its desired value, OR by placing the options and values in a configuration file, and telling tidy to read that file with the \fB-config\fR standard option:
.LP
.in 1i
\fBtidy --\fR\fIoption1 \fRvalue1 \fB--\fIoption2 \fRvalue2 [standard options ...]
.br
\fBtidy -config \fIconfig-file \fR[standard options ...]
.LP
A Tidy configuration file is simply a text file, where each option
is listed on a separate line in the form
.LP
.in 1i
\fBoption1\fR: \fIvalue1\fR
.br
\fBoption2\fR: \fIvalue2\fR
.br
etc.

.SS File manipulation
  
.TP
\fB-output <%s>\fR, \fB-o <%s>\fR
write output to the specified <file>
(\fIoutput-file: <%s>\fR)
.TP
\fB-config <%s>\fR
set configuration options from the specified <file>

.TP
\fB-file <%s>\fR, \fB-f <%s>\fR
write errors and warnings to the specified <file>
(\fIerror-file: <%s>\fR)
.TP
\fB-modify\fR, \fB-m\fR
modify the original input files
(\fIwrite-back: yes\fR)
.SS Processing directives
  
.TP
\fB-indent\fR, \fB-i\fR
indent element content
(\fIindent: auto\fR)
.TP
\fB-wrap <%s>\fR, \fB-w <%s>\fR
wrap text at the specified <column>. 0 is assumed if <column> is missing. When this option is omitted, the default of the configuration option 'wrap' applies.
(\fIwrap: <%s>\fR)
.TP
\fB-upper\fR, \fB-u\fR
force tags to upper case
(\fIuppercase-tags: yes\fR)
.TP
\fB-clean\fR, \fB-c\fR
replace FONT, NOBR and CENTER tags with CSS
(\fIclean: yes\fR)
.TP
\fB-bare\fR, \fB-b\fR
strip out smart quotes and em dashes, etc.
(\fIbare: yes\fR)
.TP
\fB-gdoc\fR, \fB-g\fR
produce clean version of html exported by Google Docs
(\fIgdoc: yes\fR)
.TP
\fB-numeric\fR, \fB-n\fR
output numeric rather than named entities
(\fInumeric-entities: yes\fR)
.TP
\fB-errors\fR, \fB-e\fR
show only errors and warnings
(\fImarkup: no\fR)
.TP
\fB-quiet\fR, \fB-q\fR
suppress nonessential output
(\fIquiet: yes\fR)
.TP
\fB-omit\fR
omit optional start tags and end tags
(\fIomit-optional-tags: yes\fR)
.TP
\fB-xml\fR
specify the input is well formed XML
(\fIinput-xml: yes\fR)
.TP
\fB-asxml\fR, \fB-asxhtml\fR
convert HTML to well formed XHTML
(\fIoutput-xhtml: yes\fR)
.TP
\fB-ashtml\fR
force XHTML to well formed HTML
(\fIoutput-html: yes\fR)
.TP
\fB-access <%s>\fR
do additional accessibility checks (<level> = 0, 1, 2, 3). 0 is assumed if <level> is missing.
(\fIaccessibility-check: <%s>\fR)
.SS Character encodings
  
.TP
\fB-raw\fR
output values above 127 without conversion to entities

.TP
\fB-ascii\fR
use ISO-8859-1 for input, US-ASCII for output

.TP
\fB-latin0\fR
use ISO-8859-15 for input, US-ASCII for output

.TP
\fB-latin1\fR
use ISO-8859-1 for both input and output

.TP
\fB-iso2022\fR
use ISO-2022 for both input and output

.TP
\fB-utf8\fR
use UTF-8 for both input and output

.TP
\fB-mac\fR
use MacRoman for input, US-ASCII for output

.TP
\fB-win1252\fR
use Windows-1252 for input, US-ASCII for output

.TP
\fB-ibm858\fR
use IBM-858 (CP850+Euro) for input, US-ASCII for output

.TP
\fB-utf16le\fR
use UTF-16LE for both input and output

.TP
\fB-utf16be\fR
use UTF-16BE for both input and output

.TP
\fB-utf16\fR
use UTF-16 for both input and output

.TP
\fB-big5\fR
use Big5 for both input and output

.TP
\fB-shiftjis\fR
use Shift_JIS for both input and output

.SS Miscellaneous
  
.TP
\fB-version\fR, \fB-v\fR
show the version of Tidy

.TP
\fB-help\fR, \fB-h\fR, \fB-?\fR
list the command line options

.TP
\fB-help-config\fR
list all configuration options

.TP
\fB-show-config\fR
list the current configuration settings

.TP
\fB-help-option <%s>\fR
show a description of the <option>

.TP
\fB-language <%s>\fR
set Tidy's output language to <lang>. Specify '-language help' for more help. Use before output-causing arguments to ensure the language takes effect, e.g.,`tidy -lang es -lang help`.
(\fIlanguage: <%s>\fR)
.SS XML
  
.TP
\fB-xml-help\fR
list the command line options in XML format

.TP
\fB-xml-config\fR
list all configuration options in XML format

.TP
\fB-xml-strings\fR
output all of Tidy's strings in XML format

.TP
\fB-xml-error-strings\fR
output error constants and strings in XML format

.TP
\fB-xml-options-strings\fR
output option descriptions in XML format

.SH USAGE
.LP
Input/Output default to stdin/stdout respectively.
.SH ENVIRONMENT
.TP
.B HTML_TIDY
Name of the default configuration file.  This should be an absolute path, since you will probably invoke \fBtidy\fR from different directories.  The value of HTML_TIDY will be parsed after the compiled-in default (defined with -DTIDY_CONFIG_FILE), but before any of the files specified using \fB-config\fR.
.SH "EXIT STATUS"
.IP 0
All input files were processed successfully.
.IP 1
There were warnings.
.IP 2
There were errors.

.SH SEE ALSO
For more information about HTML Tidy:
.RS 4
.LP
http://www.html-tidy.org/
.RE
.LP
For more information on HTML:
.RS 4
.LP
\fBHTML: Edition for Web Authors\fR (the latest HTML specification)
.br
http://dev.w3.org/html5/spec-author-view
.LP
\fBHTML: The Markup Language\fR (an HTML language reference)
.br
http://dev.w3.org/html5/markup/
.RE
.LP
For bug reports and comments:
.RS 4
.LP
https://github.com/htacg/tidy-html5/issues/
.RE
.LP
Or send questions and comments to \fBpublic-htacg@w3.org\fR.
.LP
Validate your HTML documents using the \fBW3C Nu Markup Validator\fR:
.RS 4
.LP
http://validator.w3.org/nu/
.RE
.SH AUTHOR
\fBTidy\fR was written by \fBDave Raggett\fR <dsr@w3.org>, and subsequently maintained by a team at http://tidy.sourceforge.net/,
and now maintained by \fBHTACG\fR (http://www.htacg.org).
.LP
The sources for \fBHTML Tidy\fR are available at https://github.com/htacg/tidy-html5/ under the MIT Licence.
